--SELECT * FROM GD2C2017.INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'
--use GD2C2017;
--select * from gd_esquema.Maestra;

USE [GD2C2017]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON

GO
if exists (select * from dbo.sysobjects where id =
object_id(N'[SERVOMOTOR].[FUNCIONES_ROLES]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [SERVOMOTOR].[FUNCIONES_ROLES]

GO
if exists (select * from dbo.sysobjects where id =
object_id(N'[SERVOMOTOR].[FUNCIONALIDADES]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [SERVOMOTOR].[FUNCIONALIDADES]

GO
if exists (select * from dbo.sysobjects where id =
object_id(N'[SERVOMOTOR].[ROLES_USUARIOS]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [SERVOMOTOR].[ROLES_USUARIOS]

GO
if exists (select * from dbo.sysobjects where id =
object_id(N'[SERVOMOTOR].[ROLES]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [SERVOMOTOR].[ROLES]


GO
if exists (select * from dbo.sysobjects where id =
object_id(N'[SERVOMOTOR].[SUCURSALES_USUARIOS]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [SERVOMOTOR].[SUCURSALES_USUARIOS]



GO
if exists (select * from dbo.sysobjects where id =
object_id(N'[SERVOMOTOR].[USUARIOS]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [SERVOMOTOR].[USUARIOS]


GO
if exists (select * from dbo.sysobjects where id =
object_id(N'[SERVOMOTOR].[ITEMS]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [SERVOMOTOR].[ITEMS]

GO
if exists (select * from dbo.sysobjects where id =
object_id(N'[SERVOMOTOR].[FACTURAS]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [SERVOMOTOR].[FACTURAS]

GO
if exists (select * from dbo.sysobjects where id =
object_id(N'[SERVOMOTOR].[RENDICIONES]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [SERVOMOTOR].[RENDICIONES]

GO
if exists (select * from dbo.sysobjects where id =
object_id(N'[SERVOMOTOR].[EMPRESAS]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [SERVOMOTOR].[EMPRESAS]




GO
if exists (select * from dbo.sysobjects where id =
object_id(N'[SERVOMOTOR].[PAGOS]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [SERVOMOTOR].[PAGOS]



GO
if exists (select * from dbo.sysobjects where id =
object_id(N'[SERVOMOTOR].[MEDIOS_DE_PAGO]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [SERVOMOTOR].[MEDIOS_DE_PAGO]




GO
if exists (select * from dbo.sysobjects where id =
object_id(N'[SERVOMOTOR].[SUCURSALES]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [SERVOMOTOR].[SUCURSALES]




GO
if exists (select * from dbo.sysobjects where id =
object_id(N'[SERVOMOTOR].[CLIENTES]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [SERVOMOTOR].[CLIENTES]




GO
if exists (select * from dbo.sysobjects where id =
object_id(N'[SERVOMOTOR].[RUBROS]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [SERVOMOTOR].[RUBROS]

GO
if exists (select * from dbo.sysobjects where id =
object_id(N'[SERVOMOTOR].[FACTURA_DEVOLUCION]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [SERVOMOTOR].[FACTURA_DEVOLUCION]

GO
if exists (select * from dbo.sysobjects where id =
object_id(N'[SERVOMOTOR].[RENDICION_DEVOLUCION]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [SERVOMOTOR].[RENDICION_DEVOLUCION]





GO
IF  EXISTS (SELECT * FROM sys.schemas WHERE name = N'SERVOMOTOR')
DROP SCHEMA [SERVOMOTOR]
GO

CREATE SCHEMA [SERVOMOTOR] AUTHORIZATION [gd]
GO

--//////////////////////////////////////////////



--//////////// Creacion de tablas //////////////

--Rol: Si el estado es 0, se encuentra inactivo, si es 1 activo.
--Esta tabla contiene código, nombre y estado del rol (activo/inactivo)
CREATE TABLE [SERVOMOTOR].[ROLES](
	[ID_ROL] [tinyint] IDENTITY,
	[NOMBRE] [varchar](30) UNIQUE NOT NULL, 
 CONSTRAINT [PK_ROLES] PRIMARY KEY CLUSTERED 
(
	[ID_ROL] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO


--Tabla Funcionalidad: Contiene los códigos, nombres de cada funcionalidad. 
CREATE TABLE [SERVOMOTOR].[FUNCIONALIDADES](
	[ID_FUNC] [tinyint] IDENTITY,
	[NOMBRE] [varchar] (60) UNIQUE NOT NULL,
CONSTRAINT [PK_FUNCIONALIDADES] PRIMARY KEY CLUSTERED 
(
	[ID_FUNC] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO


--Tabla Funciones por rol: Contiene las funcionalidades habilitadas para cada rol del sistema.
CREATE TABLE [SERVOMOTOR].[FUNCIONES_ROLES](
	[ID_ROL] [tinyint] NOT NULL,
	[ID_FUNC] [tinyint] NOT NULL,
 CONSTRAINT [PK_FUNCIONES_ROLES] PRIMARY KEY CLUSTERED 
(
	[ID_ROL] ASC,
	[ID_FUNC] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO


ALTER TABLE [SERVOMOTOR].[FUNCIONES_ROLES]  WITH CHECK ADD  CONSTRAINT [FK_FUNCIONES_ROLES_ROLES] FOREIGN KEY([ID_ROL])
REFERENCES [SERVOMOTOR].[ROLES] ([ID_ROL])

GO

ALTER TABLE [SERVOMOTOR].[FUNCIONES_ROLES]  WITH CHECK ADD  CONSTRAINT [FK_FUNCIONES_ROLES_FUNCIONALIDADES] FOREIGN KEY([ID_FUNC])
REFERENCES [SERVOMOTOR].[FUNCIONALIDADES] ([ID_FUNC])

GO

-- Tabla Sucursales: 
CREATE TABLE [SERVOMOTOR].[SUCURSALES](
	[COD_POSTAL] [tinyint] IDENTITY,
	[NOMBRE] [varchar] (60) UNIQUE NOT NULL,
	[DIRECCION] [varchar] (20) UNIQUE,
	[ESTADO_HABILITACION] [varchar] (70) NOT NULL,
 CONSTRAINT [PK_SUCURSALES] PRIMARY KEY CLUSTERED 
(
	[COD_POSTAL] 
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
-- Tabla Usuarios: 
CREATE TABLE [SERVOMOTOR].[USUARIOS](
	[ID_USUARIO] [tinyint] IDENTITY,
	[USERNAME] [varchar] (20) UNIQUE,
	[PASSWORD] [varchar] (70) NOT NULL,
	[HABILITADO] [bit] DEFAULT 1,
	[CANT_INT_FALL] [tinyint] DEFAULT 0,
 CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] 
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


GO

--Tabla roles por usuario: tiene los roles para cada usuario del sistema
CREATE TABLE [SERVOMOTOR].[ROLES_USUARIOS](
	[ID_ROL] [tinyint] NOT NULL,
	[ID_USUARIO] [tinyint] NOT NULL,
	[ESTADO] [varchar] (60) NOT NULL,
 CONSTRAINT [PK_ROLES_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[ID_ROL] ASC,
	[ID_USUARIO] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO


ALTER TABLE [SERVOMOTOR].[ROLES_USUARIOS]  WITH CHECK ADD  CONSTRAINT [FK_ROLES_USUARIOS_ROL] FOREIGN KEY([ID_ROL])
REFERENCES [SERVOMOTOR].[ROLES] ([ID_ROL])

GO

ALTER TABLE [SERVOMOTOR].[ROLES_USUARIOS]  WITH CHECK ADD  CONSTRAINT [FK_ROLES_USUARIOS_USUARIO] FOREIGN KEY([ID_USUARIO])
REFERENCES [SERVOMOTOR].[USUARIOS] ([ID_USUARIO])


--Tabla roles por SUCURSALES: tiene los SUCURSALES PARA CADA USUARIO
CREATE TABLE [SERVOMOTOR].[SUCURSALES_USUARIOS](
	[ID_USUARIO] [tinyint] NOT NULL,
	[COD_POSTAL] [tinyint] NOT NULL,
 CONSTRAINT [PK_SUCURSALES_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC,
	[COD_POSTAL] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO


ALTER TABLE [SERVOMOTOR].[SUCURSALES_USUARIOS]  WITH CHECK ADD  CONSTRAINT [FK_SUCURSALES_USUARIOS_USUARIO] FOREIGN KEY([ID_USUARIO])
REFERENCES [SERVOMOTOR].[USUARIOS] ([ID_USUARIO])

GO

ALTER TABLE [SERVOMOTOR].[SUCURSALES_USUARIOS]  WITH CHECK ADD  CONSTRAINT [FK_SUCURSALES_USUARIOS_SUCURSAL] FOREIGN KEY([COD_POSTAL])
REFERENCES [SERVOMOTOR].[SUCURSALES] ([COD_POSTAL])


-- Tabla Medios de pago: 
CREATE TABLE [SERVOMOTOR].[MEDIOS_DE_PAGO](
	[ID_MEDPAGO] [tinyint] IDENTITY,
	[TIPO_MEDPAGO] [varchar] (20) UNIQUE,
 CONSTRAINT [PK_MEDPAGO] PRIMARY KEY CLUSTERED 
(
	[ID_MEDPAGO] 
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


--Tabla PAGOS
CREATE TABLE [SERVOMOTOR].[PAGOS](
	[NUMERO_PAGO] [tinyint] NOT NULL,
	[FECHA_COBRO] [datetime] NOT NULL,
	[FECHA_VENCIMIENTO] [datetime] NOT NULL,
	[IMPORTE] [numeric] (7,2) NOT NULL,
	[COD_POSTAL] [tinyint] NOT NULL,
	[ID_MEDPAGO] [tinyint] NOT NULL,
 CONSTRAINT [PK_PAGOS] PRIMARY KEY CLUSTERED 
(
	[NUMERO_PAGO] 
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO


ALTER TABLE [SERVOMOTOR].[PAGOS]  WITH CHECK ADD  CONSTRAINT [FK_PAGOS_SUCURSAL] FOREIGN KEY([COD_POSTAL])
REFERENCES [SERVOMOTOR].[SUCURSALES] ([COD_POSTAL])

ALTER TABLE [SERVOMOTOR].[PAGOS]  WITH CHECK ADD  CONSTRAINT [FK_PAGOS_MEDPAGO] FOREIGN KEY([ID_MEDPAGO])
REFERENCES [SERVOMOTOR].[MEDIOS_DE_PAGO] ([ID_MEDPAGO])


-- Tabla FACTURA DEVOLUCION: 
CREATE TABLE [SERVOMOTOR].[FACTURA_DEVOLUCION](
	[ID_DEVOLUCION] [tinyint] IDENTITY,
	[MOTIVO_DEVOLUCION] [varchar] (20) UNIQUE,
 CONSTRAINT [PK_FACTURA_DEVOLUCION] PRIMARY KEY CLUSTERED 
(
	[ID_DEVOLUCION] 
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]




-- Tabla RUBROS: 
CREATE TABLE [SERVOMOTOR].[RUBROS](
	[ID_RUBRO] [tinyint] IDENTITY,
	[DESCRIPCION] [varchar] (20) UNIQUE,
 CONSTRAINT [PK_RUBROS] PRIMARY KEY CLUSTERED 
(
	[ID_RUBRO] 
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


-- Tabla EMPRESAS: 
CREATE TABLE [SERVOMOTOR].[EMPRESAS](
	[CUIT] [tinyint] IDENTITY,
	[NOMBRE] [varchar] (20) NOT NULL,
	[DIRECCION] [varchar] (20) NOT NULL,
	[ID_RUBRO] [tinyint] ,
	[ESTADO_ACTIVACION] [varchar] (20) NOT NULL,
 CONSTRAINT [PK_EMPRESAS] PRIMARY KEY CLUSTERED 
(
	[CUIT] 
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [SERVOMOTOR].[EMPRESAS]  WITH CHECK ADD  CONSTRAINT [FK_EMPRESAS_RUBRO] FOREIGN KEY([ID_RUBRO])
REFERENCES [SERVOMOTOR].[RUBROS] ([ID_RUBRO])


-- Tabla RENDICION DEVOLUCION: 
CREATE TABLE [SERVOMOTOR].[RENDICION_DEVOLUCION](
	[ID_DEVOLUCION] [tinyint] IDENTITY,
	[MOTIVO_DEVOLUCION] [varchar] (20) NOT NULL,
 CONSTRAINT [PK_RENDICION_DEVOLUCION] PRIMARY KEY CLUSTERED 
(
	[ID_DEVOLUCION] 
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


-- Tabla RENDICIONES: 
CREATE TABLE [SERVOMOTOR].[RENDICIONES](
	[ID_RENDICION] [tinyint] IDENTITY,
	[FECHA_COBRO] [datetime] NOT NULL,
	[PORCENTAJE_COMISION]  [tinyint] NOT NULL,
	[CANTIDAD_FACTURAS_RENDIDAS] [tinyint] NOT NULL,
	[PRECIO_COMISION] [numeric] (7,2) NOT NULL,
	[TOTAL_RENDIDO] [numeric] (7,2) NOT NULL,
	[ESTADO] [varchar] (20) NOT NULL,
	[ID_DEVOLUCION] [tinyint],
	[CUIT_EMPRESA] [tinyint],
 CONSTRAINT [PK_RENDICIONES] PRIMARY KEY CLUSTERED 
(
	[ID_RENDICION] 
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [SERVOMOTOR].[RENDICIONES]  WITH CHECK ADD  CONSTRAINT [FK_RENDICIONES_DEVOLUCION] FOREIGN KEY([ID_DEVOLUCION])
REFERENCES [SERVOMOTOR].[RENDICION_DEVOLUCION] ([ID_DEVOLUCION])

ALTER TABLE [SERVOMOTOR].[RENDICIONES]  WITH CHECK ADD  CONSTRAINT [FK_RENDICIONES_EMPRESA] FOREIGN KEY([CUIT_EMPRESA])
REFERENCES [SERVOMOTOR].[EMPRESAS] ([CUIT])


-- Tabla CLIENTES: 
CREATE TABLE [SERVOMOTOR].[CLIENTES](
	[DNI] [tinyint] IDENTITY,
	[NOMBRE] [varchar] (20) NOT NULL,
	[APELLIDO] [varchar] (20) NOT NULL,
	[MAIL] [varchar] (20) NOT NULL,
	[TELEFONO] [varchar] (20) NOT NULL,
	[CALLE] [varchar] (20) NOT NULL,
	[PISO] [varchar] (20) NOT NULL,
	[DEPTO] [varchar] (20) NOT NULL,
	[LOCALIDAD] [varchar] (20) NOT NULL,
	[FECHA_NACIMIENTO] [datetime] NOT NULL,
	[COD_POSTAL_CLIENTE] [varchar] (20) NOT NULL,
	[ESTADO_HABILITACION] [varchar] (20) NOT NULL,
 CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED 
(
	[DNI] 
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]



-- Tabla FACTURAS: 
CREATE TABLE [SERVOMOTOR].[FACTURAS](
	[NUMERO_FACTURA] [tinyint] IDENTITY,
	[FECHA_ALTA] [datetime] NOT NULL,
	[FECHA_VENCIMIENTO] [datetime] NOT NULL,
	[DNI_CLIENTE] [tinyint] NOT NULL,
	[CUIT_EMPRESA] [tinyint] NOT NULL,
	[TOTAL] [numeric] (7,2) NOT NULL,
	[ESTADO] [varchar] (20) NOT NULL,
	[NUMERO_PAGO] [tinyint] NOT NULL,
	[ID_RENDICION] [tinyint] NOT NULL,
	[ID_DEVOLUCION] [tinyint] NOT NULL,
 CONSTRAINT [PK_FACTURAS] PRIMARY KEY CLUSTERED 
(
	[NUMERO_FACTURA] 
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [SERVOMOTOR].[FACTURAS]  WITH CHECK ADD  CONSTRAINT [FK_FACTURAS_CLIENTE] FOREIGN KEY([DNI_CLIENTE])
REFERENCES [SERVOMOTOR].[CLIENTES] ([DNI])

ALTER TABLE [SERVOMOTOR].[FACTURAS]  WITH CHECK ADD  CONSTRAINT [FK_FACTURAS_EMPRESA] FOREIGN KEY([CUIT_EMPRESA])
REFERENCES [SERVOMOTOR].[EMPRESAS] ([CUIT])

ALTER TABLE [SERVOMOTOR].[FACTURAS]  WITH CHECK ADD  CONSTRAINT [FK_FACTURAS_PAGOS] FOREIGN KEY([NUMERO_PAGO])
REFERENCES [SERVOMOTOR].[PAGOS] ([NUMERO_PAGO])

ALTER TABLE [SERVOMOTOR].[FACTURAS]  WITH CHECK ADD  CONSTRAINT [FK_FACTURAS_RENDICION] FOREIGN KEY([ID_RENDICION])
REFERENCES [SERVOMOTOR].[RENDICIONES] ([ID_RENDICION])

ALTER TABLE [SERVOMOTOR].[FACTURAS]  WITH CHECK ADD  CONSTRAINT [FK_FACTURAS_DEVOLUCION] FOREIGN KEY([ID_DEVOLUCION])
REFERENCES [SERVOMOTOR].[FACTURA_DEVOLUCION] ([ID_DEVOLUCION])



-- Tabla ITEMS: 
CREATE TABLE [SERVOMOTOR].[ITEMS](
	[ID_ITEM] [tinyint] IDENTITY,
	[DESCRIPCION] [varchar] (20) NOT NULL,
	[MONTO] [numeric] (7,2) NOT NULL,
	[IMPORTE] [numeric] (7,2) NOT NULL,
	[CANTIDAD] [tinyint] NOT NULL,
	[NUMERO_FACTURA] [tinyint] NOT NULL,
 CONSTRAINT [PK_ITEMS] PRIMARY KEY CLUSTERED 
(
	[ID_ITEM] 
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


ALTER TABLE [SERVOMOTOR].[ITEMS]  WITH CHECK ADD  CONSTRAINT [FK_ITEMS_PAGO] FOREIGN KEY([NUMERO_FACTURA])
REFERENCES [SERVOMOTOR].[FACTURAS] ([NUMERO_FACTURA])